### ISSUE TITLE
Package name typos yield confusing error

### ISSUE THREAD

**Issue by peterbe** [peterbe/hashin#13]
For example, I got this:

```
$ hashin djang-waffle
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/socorro/bin/hashin", line 11, in <module>
    sys.exit(main())
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/hashin.py", line 189, in main
    verbose=args.verbose,
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/hashin.py", line 53, in run
    data = get_package_data(package, verbose)
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/hashin.py", line 120, in get_package_data
    content = json.loads(_download(url))
  File "/opt/boxen/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/boxen/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/boxen/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Note the typo `djang-waffle`.

**Comment by peterbe** [comment]
Too old.
