### ISSUE TITLE
Python 3.13 support (i.e. need to migrate off of stdlib package `cgi`)

### ISSUE THREAD

**Issue by hartwork** [peterbe/hashin#160]
This is the official messaging about it:

```console
# pytest -v |& grep -A3 'warnings summary' | sed "s,${PWD},[..],"
=============================== warnings summary ===============================
hashin.py:10
  [..]/hashin.py:10: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

Let's get pull request #159 merged first, though.

**Comment by hartwork** [comment]
Update: Python 3.13 has been released.

```console
# hashin --help
Traceback (most recent call last):
  File "/tmp/tmp.EWI8aI2WD6/venv/bin/hashin", line 5, in <module>
    from hashin import main
  File "/tmp/tmp.EWI8aI2WD6/venv/lib/python3.13/site-packages/hashin.py", line 10, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'
```
