### ISSUE TITLE
Unrecognizable url Error

### ISSUE THREAD

**Issue by jayfk** [peterbe/hashin#32]
This one works:
```
hashin turbine
```

This one doesn't:
```
hashin turbine --python-version 2.7
```

```
Traceback (most recent call last):
  File "/Users/j/dev/.virtualenvs/hashin/bin/hashin", line 11, in <module>
    sys.exit(main())
  File "/Users/j/dev/.virtualenvs/hashin/lib/python3.5/site-packages/hashin.py", line 331, in main
    verbose=args.verbose,
  File "/Users/j/dev/.virtualenvs/hashin/lib/python3.5/site-packages/hashin.py", line 63, in run
    run_single_package(spec, *args, **kwargs)
  File "/Users/j/dev/.virtualenvs/hashin/lib/python3.5/site-packages/hashin.py", line 92, in run_single_package
    releases = filter_releases(releases, python_versions)
  File "/Users/j/dev/.virtualenvs/hashin/lib/python3.5/site-packages/hashin.py", line 255, in filter_releases
    metadata = release_url_metadata(release['url'])
  File "/Users/j/dev/.virtualenvs/hashin/lib/python3.5/site-packages/hashin.py", line 248, in release_url_metadata
    raise PackageError('Unrecognizable url: ' + url)
hashin.PackageError: Unrecognizable url: https://pypi.python.org/packages/a4/ae/65500d0becffe3dd6671fbdc6010cc0c4a8b715dbd94315ba109bbc54bc5/turbine-0.0.3.linux-x86_64.tar.gz
```

**Comment by peterbe** [comment]
@mythmon Have you seen this too?

**Comment by mythmon** [comment]
I haven't run into this (yet?), but it looks pretty straight forward. It seems pypi added a new kind of hash. This one looks longer, maybe it is sha512?
