### ISSUE TITLE
Typos cause ugly ValueErrors

### ISSUE THREAD

**Issue by peterbe** [peterbe/hashin#48]
E.g.
```
▶ hashin -r /tmp/reqs.txt Djaungo
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/hashin/bin/hashin", line 9, in <module>
    load_entry_point('hashin', 'console_scripts', 'hashin')()
  File "/Users/peterbe/dev/PYTHON/hashin/hashin.py", line 433, in main
    verbose=args.verbose,
  File "/Users/peterbe/dev/PYTHON/hashin/hashin.py", line 104, in run
    run_single_package(spec, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/hashin/hashin.py", line 127, in run_single_package
    algorithm=algorithm
  File "/Users/peterbe/dev/PYTHON/hashin/hashin.py", line 374, in get_package_hashes
    data = get_package_data(package, verbose)
  File "/Users/peterbe/dev/PYTHON/hashin/hashin.py", line 311, in get_package_data
    content = json.loads(_download(url))
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The culprit appears (just looking at the traceback) to be: ` json.loads(_download(url))` 
when instead, the download should probably raise its own exception if the URL is no good.

**Comment by peterbe** [comment]
Fixed with https://github.com/peterbe/hashin/commit/d4c626fee95d3b3ac229e6f57790e37e18c4c05c
