### ISSUE TITLE
`hashin black` fails

### ISSUE THREAD

**Issue by peterbe** [peterbe/hashin#64]
```
▶ hashin black
Traceback (most recent call last):
  File "/usr/local/bin/hashin", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 474, in main
    verbose=args.verbose,
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 120, in run
    run_single_package(spec, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 146, in run_single_package
    algorithm=algorithm
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 407, in get_package_hashes
    version = get_latest_version(data)
  File "/usr/local/lib/python3.6/site-packages/hashin.py", line 223, in get_latest_version
    return str(all_versions[0][1])
IndexError: list index out of range
```

**Comment by peterbe** [comment]
The reason it fails is because there isn't a single non-prerelease version in the JSON.
